/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      },
      spacing: {
        "gutter": "24px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        "unit": "8px",
        "section-margin": "64px",
        "card-gap": "24px"
      },
      colors: {
        "secondary-fixed": "#ffdea6",
        "on-primary-container": "#bcd0ff",
        "on-background": "#d6e3ff",
        "surface-dim": "#041329",
        "surface-container": "#112036",
        "inverse-primary": "#305caa",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#05297a",
        "surface-container-high": "#1c2a41",
        "on-primary": "#002e6a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#d6e3ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#010e24",
        "surface-container-low": "#0d1c32",
        "on-tertiary-fixed-variant": "#264191",
        "surface-container-highest": "#27354c",
        "surface-variant": "#27354c",
        "surface-bright": "#2c3951",
        "on-tertiary-container": "#c3ceff",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#00164e",
        "on-secondary": "#412d00",
        "outline": "#8d909c",
        "on-primary-fixed": "#001a42",
        "primary-container": "#2957a4",
        "on-surface-variant": "#c3c6d3",
        "on-secondary-container": "#d8b372",
        "surface-tint": "#adc6ff",
        "surface": "#041329",
        "secondary-container": "#5e450d",
        "tertiary": "#b6c4ff",
        "tertiary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#e7c17e",
        "outline-variant": "#434751",
        "on-surface": "#d6e3ff",
        "on-primary-fixed-variant": "#0c4490",
        "on-error": "#690005",
        "inverse-on-surface": "#233148",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#3b54a5",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5c420b",
        "tertiary-fixed-dim": "#b6c4ff",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
